logging:
  level:
    com.st.workspace: debug

server:
  port: 8080

spring:
  application:
    name: com.st.workspace
  data.mongodb:
    password: phouwahshaeve2aireiC
    username: dev-user
    database: workspaces
    host: stl-docdb-be-dev01.cluster-c4gebpgnh17l.us-east-1.docdb.amazonaws.com
    port: 27021

mongock:
  change-logs-scan-package: com.st.workspace.config
